// ─── Route Constants ──────────────────────────────────────────────────────────
export const ROUTES = {
  // Public
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:slug',
  CATEGORIES: '/categories',
  CATEGORY_DETAIL: '/categories/:slug',
  BRANDS: '/brands',
  BRAND_DETAIL: '/brands/:slug',
  SEARCH: '/search',
  PROMOTIONS: '/promotions',
  BLOGS: '/blogs',
  BLOG_DETAIL: '/blogs/:slug',
  SHOPS: '/shops',
  SHOP_DETAIL: '/shops/:slug',
  CONTACT: '/contact',
  ABOUT: '/about',
  FAQ: '/faq',

  // Auth
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',

  // Customer (protected - CUSTOMER)
  ACCOUNT: '/account',
  ACCOUNT_DASHBOARD: '/account/dashboard',
  ORDERS: '/orders',
  ORDER_DETAIL: '/orders/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  WISHLIST: '/wishlist',
  COMPARE: '/compare',
  RECENTLY_VIEWED: '/recently-viewed',
  ADDRESSES: '/addresses',
  PAYMENTS: '/payments',
  NOTIFICATIONS: '/notifications',
  SUPPORT: '/support',

  // Shop (protected - SHOP)
  SHOP_DASHBOARD: '/shop/dashboard',
  SHOP_PRODUCTS: '/shop/products',
  SHOP_PRODUCT_CREATE: '/shop/products/create',
  SHOP_PRODUCT_EDIT: '/shop/products/edit/:id',
  SHOP_ORDERS: '/shop/orders',
  SHOP_INVENTORY: '/shop/inventory',
  SHOP_PROMOTIONS: '/shop/promotions',
  SHOP_REVIEWS: '/shop/reviews',
  SHOP_REPORTS: '/shop/reports',
  SHOP_FINANCE: '/shop/finance',
  SHOP_PAYMENTS: '/shop/payments',
  SHOP_SUPPORT: '/shop/support',
  SHOP_PROFILE: '/shop/profile',

  // Admin (protected - ADMIN, SUPER_ADMIN)
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_SHOPS: '/admin/shops',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_PROMOTIONS: '/admin/promotions',
  ADMIN_SUPPORT: '/admin/support',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_ROLES: '/admin/roles',

  // Errors
  NOT_FOUND: '/404',
  FORBIDDEN: '/403',
  SERVER_ERROR: '/500',
} as const;

// ─── Page Title Mapping ─────────────────────────────────────────────────────
export const PAGE_TITLES: Record<string, string> = {
  [ROUTES.HOME]: 'Trang Chủ',
  [ROUTES.PRODUCTS]: 'Sản Phẩm',
  [ROUTES.PRODUCT_DETAIL]: 'Chi Tiết Sản Phẩm',
  [ROUTES.CATEGORIES]: 'Danh Mục',
  [ROUTES.CATEGORY_DETAIL]: 'Danh Mục',
  [ROUTES.BRANDS]: 'Thương Hiệu',
  [ROUTES.BRAND_DETAIL]: 'Thương Hiệu',
  [ROUTES.SEARCH]: 'Tìm Kiếm',
  [ROUTES.PROMOTIONS]: 'Khuyến Mãi',
  [ROUTES.BLOGS]: 'Blog Công Nghệ',
  [ROUTES.BLOG_DETAIL]: 'Bài Viết',
  [ROUTES.SHOPS]: 'Cửa Hàng',
  [ROUTES.SHOP_DETAIL]: 'Cửa Hàng',
  [ROUTES.CONTACT]: 'Liên Hệ',
  [ROUTES.ABOUT]: 'Giới Thiệu',
  [ROUTES.FAQ]: 'Câu Hỏi Thường Gặp',
  [ROUTES.LOGIN]: 'Đăng Nhập',
  [ROUTES.REGISTER]: 'Đăng Ký',
  [ROUTES.FORGOT_PASSWORD]: 'Quên Mật Khẩu',
  [ROUTES.ACCOUNT]: 'Tài Khoản',
  [ROUTES.ACCOUNT_DASHBOARD]: 'Tài Khoản',
  [ROUTES.ORDERS]: 'Đơn Hàng',
  [ROUTES.ORDER_DETAIL]: 'Chi Tiết Đơn Hàng',
  [ROUTES.CART]: 'Giỏ Hàng',
  [ROUTES.CHECKOUT]: 'Thanh Toán',
  [ROUTES.WISHLIST]: 'Yêu Thích',
  [ROUTES.COMPARE]: 'So Sánh',
  [ROUTES.RECENTLY_VIEWED]: 'Đã Xem Gần Đây',
  [ROUTES.ADDRESSES]: 'Địa Chỉ',
  [ROUTES.PAYMENTS]: 'Thanh Toán',
  [ROUTES.NOTIFICATIONS]: 'Thông Báo',
  [ROUTES.SUPPORT]: 'Hỗ Trợ',
  [ROUTES.SHOP_DASHBOARD]: 'Dashboard Shop',
  [ROUTES.SHOP_PRODUCTS]: 'Quản Lý Sản Phẩm',
  [ROUTES.SHOP_PRODUCT_CREATE]: 'Thêm Sản Phẩm',
  [ROUTES.SHOP_PRODUCT_EDIT]: 'Sửa Sản Phẩm',
  [ROUTES.SHOP_ORDERS]: 'Quản Lý Đơn Hàng',
  [ROUTES.SHOP_INVENTORY]: 'Quản Lý Kho',
  [ROUTES.SHOP_PROMOTIONS]: 'Khuyến Mãi Shop',
  [ROUTES.SHOP_REVIEWS]: 'Quản Lý Đánh Giá',
  [ROUTES.SHOP_REPORTS]: 'Báo Cáo',
  [ROUTES.SHOP_FINANCE]: 'Tài Chính',
  [ROUTES.SHOP_PAYMENTS]: 'Thanh Toán Shop',
  [ROUTES.SHOP_SUPPORT]: 'Hỗ Trợ Shop',
  [ROUTES.SHOP_PROFILE]: 'Cài Đặt Cửa Hàng',
  [ROUTES.ADMIN_DASHBOARD]: 'Dashboard Admin',
  [ROUTES.ADMIN_PRODUCTS]: 'Quản Lý Sản Phẩm',
  [ROUTES.ADMIN_ORDERS]: 'Quản Lý Đơn Hàng',
  [ROUTES.ADMIN_CUSTOMERS]: 'Quản Lý Khách Hàng',
  [ROUTES.ADMIN_SHOPS]: 'Quản Lý Shop',
  [ROUTES.ADMIN_PAYMENTS]: 'Quản Lý Thanh Toán',
  [ROUTES.ADMIN_REVIEWS]: 'Quản Lý Đánh Giá',
  [ROUTES.ADMIN_PROMOTIONS]: 'Quản Lý Khuyến Mãi',
  [ROUTES.ADMIN_SUPPORT]: 'Quản Lý Hỗ Trợ',
  [ROUTES.ADMIN_REPORTS]: 'Báo Cáo Hệ Thống',
  [ROUTES.ADMIN_ROLES]: 'Phân Quyền',
  [ROUTES.NOT_FOUND]: '404 - Không Tìm Thấy',
  [ROUTES.FORBIDDEN]: '403 - Không Có Quyền Truy Cập',
  [ROUTES.SERVER_ERROR]: '500 - Lỗi Hệ Thống',
};

export const APP_NAME = 'HenzoStore';
export const APP_TAGLINE = 'Công Nghệ Hàng Đầu';
